### ISSUE TITLE
How to use a token for Proxmox provider? (alternatively: this might need to be regenerated from tf source)

### ISSUE THREAD

**Issue by spott** [muhlba91/pulumi-proxmoxve#12]
I'm trying to use a token to connect to my Proxmox instance, unfortunately, I'm getting the following:

```
❯ pulumi up
Previewing update (infra):
     Type                            Name               Plan     Info
     pulumi:pulumi:Stack             unbound_dns-infra
     └─ proxmoxve:VM:VirtualMachine  unbound_vm                  1 error

Diagnostics:
  proxmoxve:VM:VirtualMachine (unbound_vm):
    error: could not validate provider configuration: 1 error occurred:
    	* You must specify a password for the Proxmox Virtual Environment API
```

I tried to look at the source terraform Proxmox repo, however the linked one (https://github.com/bpg/terraform-provider-proxmoxve/issues) 404s.  A similar one (at least in name) with the same name is here: https://github.com/Telmate/terraform-provider-proxmox, which has been updated fairly recently.

As an aside, I couldn't figure out how the password was required (where in the code that is enforced) as all the options to the provider are listed as optional.

**Comment by spott** [comment]
The telmate repo might be a better source for this anyways, as It explicitly allows for tokens: (https://github.com/Telmate/terraform-provider-proxmox/blob/fb947eb03238d302a9d6aac0678ba738fced9335/proxmox/provider.go#L65), as well as a number of other features (such as LXC containers).

**Comment by spott** [comment]
Ok, it looks like I misunderstood somethings...

The link in `sdk/python/pulumi_proxmoxve` to the repo is wrong (it should be https://github.com/bpg/terraform-provider-proxmox/issues instead).  This package does support containers (I'm just blind).

I'm just going to close this, as I don't think it is relevant.

**Comment by HWiese1980** [comment]
If you have a solution for this problem, please provide it! I'm trying to get this to work too. Thank you!
