### ISSUE TITLE
No parity with upstream tf proxmox provider

### ISSUE THREAD

**Issue by pcuci** [muhlba91/pulumi-proxmoxve#122]
Thanks for maintaining this project @muhlba91 !

I think we might be out of sync with the upstream provider, e.g.:

https://github.com/bpg/terraform-provider-proxmox/blame/dd9ffe190cd9eaee7ac6a9e2c830eee45b4b69df/proxmox/virtual_environment_container_types.go#L22

No mention of cloning from snapshots here: https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/types/input.ts#L27 (I only see a subset of the upstream available options)

What would you suggest? Been trying to wrap my head around how pulumi uses the tf bridge to dynamically create the matching resources, just can't figure out who/what/when the updates are being called(?)

**Comment by muhlba91** [comment]
hi,

there's a difference in the TF internal requests and types for communicating with the Proxmox APIs, and what the upstream provider exposes in the TF resources.

what you referred to (https://github.com/bpg/terraform-provider-proxmox/blob/dd9ffe190cd9eaee7ac6a9e2c830eee45b4b69df/proxmox/virtual_environment_container.go) are the internals of the TF provider itself - for example, this is easiest to see by the fact that this file performs requests to the Proxmox API.

the other part is what the TF provider exposes in its resources which can be found here: https://github.com/bpg/terraform-provider-proxmox/tree/dd9ffe190cd9eaee7ac6a9e2c830eee45b4b69df/proxmoxtf, and for the container resource in particular here: https://github.com/bpg/terraform-provider-proxmox/blob/dd9ffe190cd9eaee7ac6a9e2c830eee45b4b69df/proxmoxtf/resource_virtual_environment_container.go#L110

comparing the container resource's clone configuration in TF and this Pulumi provider shows the same attributes:

1. TF provider (https://github.com/bpg/terraform-provider-proxmox/blob/dd9ffe190cd9eaee7ac6a9e2c830eee45b4b69df/proxmoxtf/resource_virtual_environment_container.go#L113-L147):
- datastore id
- node name
- vm id

2. Pulumi provider: https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/types/input.ts#L27-L31
- datastore id
- node name
- vm id

additionally, the TF provider documentation also only shows these 3 attributes: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container#clone

looking at this i wouldn't see any difference or drift between the providers.

**Comment by pcuci** [comment]
> additionally, the TF provider documentation also only shows these 3 attributes: https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container#clone

I see what you mean; while the tf provider might use the snapshot mechanism to do its job, it doesn't expose that publicly

The reason I wanted access to the snapshot field was to avoid first having to shutdown the running container in order to clone it.

_"Cannot do full clones on a running container without snapshots (500)"_ 

This proxmox error tripped me :-). I took it to mean that I could clone a running container if it had a snapshot, but I just tested via the web ui, and it fails. What I think PVE means is I need both* a snapshot and a stopped container to trigger a clone :-)

Thanks again for clarifying what's going on!

**Comment by muhlba91** [comment]
no worries. i know some of these error messages can be daunting - it happened to me a few times with different providers as well…

however, if you need support for a specific feature or attribute, i recommend to open an upstream issue. once upstream implemented it, it‘ll be available in this Pulumi provider as well after updating the upstream reference.

i‘ll be closing this issue in fact but feel free to reopen it or link an upstream issue to it. :)
