### ISSUE TITLE
.Net Sample

### ISSUE THREAD

**Issue by Hantse** [muhlba91/pulumi-proxmoxve#15]
Hello,

I try follow documentation, but actually i cannot deploy VM on Proxmox with C#.

I have no error message, can you give a little working sample ?

Kind regards,

**Comment by muhlba91** [comment]
unfortunately, i am not using C# myself. the sdk is autogenerated by the underlying boilerplate provided by pulumi.

could you maybe post a small sample and pulumi output? maybe there‘s something to be spot causing this issue.
