### ISSUE TITLE
How to disable replacing CTs on `pulumi up`?

### ISSUE THREAD

**Issue by pcuci** [muhlba91/pulumi-proxmoxve#174]
Can't figure out the pulumi, or tf-provider, option to not replace the CTs on every `pulumi up`

Is this allowed, possible?

Not sure I understand the rationale to always recreate the containers on `pulumi up`, the behaviour for VMs is exactly the opposite, IMO the expected behaviour (ie: update/patch, not replace).

**Comment by muhlba91** [comment]
can you please provide an example, and the outcome of a `pulumi preview`?
i suppose something changed that forces replacement; for this it's necessary to have as many details as possible.

**Comment by muhlba91** [comment]
your code doesn‘t set the `disk` property. hence, the default one applies and i guess then a diff is detected. when previewing, can you select `details` to see what exactly changed in the `disk` property?
that should give you a hint on what you need to set in your code to propose the same configuration than the container has after creation.

if you really don‘t want/need to set the `disk` property a simple way to ignore that property is the pulumi resource option [`ignoreChanges`](https://www.pulumi.com/docs/concepts/options/ignorechanges/) to be set to `['disk']`.

**Comment by pcuci** [comment]
Fantastic, with `ignoreChanges` I get the "desired" behaviour:

![image](https://github.com/muhlba91/pulumi-proxmoxve/assets/2169849/1ebdc1e5-be39-41d8-8790-e956b76b6ca4)

I'll probably just daisy chain the `disk` property from the template to the containers, to avoid the default reset, and stay explicit about what's happening.

Thank you very much!
