### ISSUE TITLE
Error on create ct

### ISSUE THREAD

**Issue by njguibert** [muhlba91/pulumi-proxmoxve#21]
Hello!
i have a problem on creating a lxc container, in facts, the lxc created in pve. But alway show the next error in the ends:
![imagen](https://user-images.githubusercontent.com/756856/206570125-44b7d0f4-7f69-4e97-8e63-baa22670da09.png)

Thank you very much!

**Comment by muhlba91** [comment]
hi,

1/ could you please also show an example of the container definition you try to use in e.g. nodejs/typescript/python/go? that would help a lot in knowing what inputs you set and what values they have. in particula the `datastore_id` is of interest here.

2/ the provider is built on the underlying terraform provider. did you have a chance to verify the same example configuration using terraform?

**Comment by njguibert** [comment]
Hello @muhlba91 ! 
thank you very mutch for the response, i'm using nodejs and this is my container definition:

const lxc = new proxmox.ct.Container('ct',{
    nodeName: 'pve01',
    description: "Contenedor generado con pulumi",
    disks: [{
        datastoreId: "local-lvm",
        size: 8,
    }],
    memory: {
        dedicated: 512,
        swap: 512,
    },
    onBoot: true,
    initialization: {
    	hostname: "lxc-01",
    	IpConfigs:[{
    		ipv4: {
    			address: "192.168.25.50/24",
    			gateway: "192.168.25.1",
    		},
    	}]
    },
    networkInterfaces: [{
        name: "veth0",
        bridge: "vmbr0",
    },],
    operatingSystem: {
        templateFileId: "local:vztmpl/debian-11-standard_11.3-1_amd64.tar.zst",
        type: "debian"
    },},
    {
        provider: provider
    },
);

Also tested same definition in terraform and work great.

**Comment by muhlba91** [comment]
please try using the `disk` property. i don't see a property `disks`, and neither is this property a list - only one disk can be defined for a container. please also update to `2.3.0`

**Comment by njguibert** [comment]
Hi!!! problem solve with update 2.3.0
Thks!!!
