### ISSUE TITLE
Add HA group support

### ISSUE THREAD

**Issue by jtamas96** [muhlba91/pulumi-proxmoxve#224]
The upstream provider supports creating HA groups and HA resources.
It would be good to have this also in the Pulumi provider.

**Comment by muhlba91** [comment]
i finally had some time to dig into this and consult some guys from pulumi. i‘m working on adding support for these resources in #260 and i hope to have it finished some time in the coming week. i‘ll ping you when a new version is out. 😃 

sorry for the late response and work on it. it took a while to have the capacity and knowing what options there are to support this scenario from the upstream provider.

**Comment by muhlba91** [comment]
this is implemented in `v6.0.0` - i'm closing this issue now. 😃

**Comment by jtamas96** [comment]
Great, thanks! :)
