### ISSUE TITLE
Missing pool id after pool import leads to recreating the pool

### ISSUE THREAD

**Issue by jtamas96** [muhlba91/pulumi-proxmoxve#229]
After importing an existing pool, the resource is missing the poolId paramaeter.
On the first pulumi up, tries to recreate the imported pool because it detects the difference between the empty pool id and the real one on the Proxmox server.

Aftter the pool import, the following warning can be seen:

![image](https://github.com/muhlba91/pulumi-proxmoxve/assets/25171705/01105302-0818-455b-acda-b3c48d62e75a)

**Comment by muhlba91** [comment]
this provider is based on the terraform provider (https://github.com/bpg/terraform-provider-proxmox), and actually only wraps its functions for pulumi. did you verify if this issue also exists when directly using the terraform provider?

**Comment by jtamas96** [comment]
Hi, thanks for the feedback.
I just checked it and the problem is present in the TF provider too.

I created an issue there:
https://github.com/bpg/terraform-provider-proxmox/issues/963

**Comment by muhlba91** [comment]
upstream fixed released with Pulumi provider version `v5.23.0`.
