### ISSUE TITLE
Container: Disk size missing

### ISSUE THREAD

**Issue by teyhouse** [muhlba91/pulumi-proxmoxve#25]
Please check the terraform provider regarding the disk options:
https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_container#size

This (optional value) is currently missing on the pulumi provider:
https://www.pulumi.com/registry/packages/proxmoxve/api-docs/ct/container/#containerdisk

This will result in containers default size of 4GB, which is not optimal in all use-cases.
Could you maybe add that?

**Comment by muhlba91** [comment]
please try with `2.3.0` - the property is now available (https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/nodejs/types/input.ts#L41).
