### ISSUE TITLE
Invalid Go SDK module

### ISSUE THREAD

**Issue by pandatix** [muhlba91/pulumi-proxmoxve#276]
Hey, due to the recent major version 6, the `sdk` Golang submodule is invalid as for #37.
Seems like the automatic process to handle this did not work as expected ☹️

**Comment by muhlba91** [comment]
`v6.0.2` (release pipeline running as wekk speak) contains this fix. sorry for that - for the previous major version updates all worked fine. it seems there's a bug in release-please.

**Comment by pandatix** [comment]
No problem, thanks for your quick reaction !
