### ISSUE TITLE
pulumi hangs if passing the 'started: true' option.

### ISSUE THREAD

**Issue by jebarpg** [muhlba91/pulumi-proxmoxve#326]
I'm able to create vms just fine with the 'started: false' but when I try to use 'started: true' to have the machines start up as soon as they are made pulumi hangs indefinitely. Is there something else that I need to take into consideration when create a vm and having it started after creation? or is this a bug?

**Comment by jebarpg** [comment]
hmm well I waited for 15 mins and it finally finished creating the vms... is this normal?

**Comment by jebarpg** [comment]
I think I found the issue. The vm didn't have qemu-guest-agent installed on it, so once I installed that it now completes tasks in about 31 seconds instead of 15 mins.

**Comment by muhlba91** [comment]
there's also a `agent.enabled` parameter which if set to false will assume the machine is started once the start command of proxmox is successful.
if this is set to true, the provider waits until the guest agent is started and reports the machine as started.

**Comment by jebarpg** [comment]
@muhlba91 am curious how to get the local ip address to print out after pulumi creates and starts up the vm?
