### ISSUE TITLE
Add /v3 to Go module

### ISSUE THREAD

**Issue by pandatix** [muhlba91/pulumi-proxmoxve#37]
The Go module under `sdk` has a malformed name. It currently is defined as `github.com/muhlba91/pulumi-proxmoxve/sdk`, but its import fails has it needs to be followed by `/v3`. See error at [sum.golang.org](https://sum.golang.org/lookup/github.com/muhlba91/pulumi-proxmoxve/sdk/v3@v3.1.0).

To provide a solve I suggest you add the `/v3` to Go module [as I did in a fork](https://github.com/pandatix/pulumi-proxmoxve/blob/main/sdk/go.mod#L1), and create a new release with tag `sdk/vX.Y.Z` (see #9). May I suggest `v3.1.1` ?

Of course, don't replace your name with mine as I did, it was just to troubleshoot more efficiently :wink:
Thanks for your work !

**Comment by pandatix** [comment]
Thanks for the fix !

**Comment by pandatix** [comment]
Hi again, there are relicas of `v3` in `v4` code generated by `tfgen`.
For instance https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/go/proxmoxve/vm/getVirtualMachines.go#L10 points to `v3` which can't get fetched due to this issue.

**Comment by muhlba91** [comment]
Hi, the line you referenced is for the Pulumi SDK directly (`github.com/pulumi/pulumi/sdk/v3/go/pulumi`).
If Pulumi doesn't provide the proper versioning, can you please open an issue with Pulumi? :)

**Comment by pandatix** [comment]
Oh... sorry wrong URL. Here is the line I wanted to target: https://github.com/muhlba91/pulumi-proxmoxve/blob/main/sdk/go/proxmoxve/vm/init.go#L10

**Comment by muhlba91** [comment]
Thank you for pointing this out! Deleting and regenerating these autogenerated files had to be done.
This is now fixed in ' 4.0.1`. (I was not able to find any references to `github.com/muhlba91/pulumi-proxmoxve/sdk/v3` anymore).
