### ISSUE TITLE
Empty CD rom is always created

### ISSUE THREAD

**Issue by janosi96** [muhlba91/pulumi-proxmoxve#396]
Since some versions, when creating a machine, an empty CD rom always get's created by default.
I have tested it with the latest version of the provider, and it's still happening.

I can't reproduce it in the latest version of the terraform provider.

**Comment by muhlba91** [comment]
hi,

could you post a short example of your Pulumi code?

currently, I believe that this might be expected behavior due to the way the pulumi-terraform-bridge works and evaluates arguments, especially if they are `null/undefined` and/or have defaults specified.

**Comment by janosi96** [comment]
Here is a minimal code to reproduce
`func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		vm, err := vm.NewVirtualMachine(ctx, "example-vm", &vm.VirtualMachineArgs{
			Name:     pulumi.String("example-vm"),
			NodeName: pulumi.String("devops-proxmox12"),
			Memory: vm.VirtualMachineMemoryArgs{
				Dedicated: pulumi.Int(1024),
			},
			Cpu: vm.VirtualMachineCpuArgs{
				Sockets: pulumi.Int(1),
				Cores:   pulumi.Int(2),
			},
			Disks: vm.VirtualMachineDiskArray{
				vm.VirtualMachineDiskArgs{
					Interface:   pulumi.String("scsi0"),
					DatastoreId: pulumi.String("ceph-ha"),
					Size:        pulumi.IntPtr(17),
				},
				vm.VirtualMachineDiskArgs{
					Interface:   pulumi.String("scsi1"),
					DatastoreId: pulumi.String("ceph-ha"),
					Size:        pulumi.IntPtr(17),
				},
			},
			Clone: vm.VirtualMachineCloneArgs{
				VmId: pulumi.Int(100),
			},
		})
		if err != nil {
			return err
		}

		ctx.Export("vmID", vm.ID())
		return nil
	})
}`

It seems like it only happens when we are cloning from another VM. The source VM has no cd rom.
This behavior was not present in the past so I don't know if we can call this intended, especially because it is not the same behavior, if there is no cloning involved, and also not the same as the terraform provider.

**Comment by muhlba91** [comment]
i remember having a similar issue at some point; the easiest solution was to ignore the `cdrom` property.

afaik, the upstream provider sets some default values, and the pulumi terraform bridge sometimes interprets missing/empty values "incorrectly", meaning not how i had expected this to happen.
i guess that this might happen as well here. the proxmox API returns no cdrom which is interpreted either on the upstream side or the pulumi terraform bridge side as, most likely, unset and defines a default value, which is to add a cdrom.
