### ISSUE TITLE
Pulumi package publishing error

### ISSUE THREAD

**Issue by sean1588** [muhlba91/pulumi-proxmoxve#49]
Hello @muhlba91 

I am one of the maintainers of the Pulumi registry. There are some issues getting the latest version of your package (v5.0.0) published to our registry as it seems it is unable to locate a schema file. It looks like in your [previous version](https://github.com/muhlba91/pulumi-proxmoxve/tree/v4.1.1/provider/cmd/pulumi-resource-proxmoxve) there was one located there. This seems to no longer be the case with [5.0.0](https://github.com/muhlba91/pulumi-proxmoxve/tree/v5.0.0/provider/cmd/pulumi-resource-proxmoxve) and our publishing pipeline is giving an error since it is unable to locate a schema file. Not sure if there were some recent changes in the latest release that need to be adjusted here. Feel free to reach out and happy to assist in any way that I can!

**Comment by muhlba91** [comment]
Hi,

thank you for your report! Yes, I have gitignored all auto-generated files, and, hence, also the schema files.
It's back in starting with `v5.0.1`.
