### ISSUE TITLE
Python SDK: "grpc: received message larger than max"

### ISSUE THREAD

**Issue by joshrmcdaniel** [muhlba91/pulumi-proxmoxve#50]
When attempting to add `source_raw` to the `proxmox_virtual_environment_file` resource, I am receiving the following error:
```
Exception: grpc: received message larger than max (<size> vs. 419430400)
```
Stack Trace:
```
<parent>/venv/Lib/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "grpc: received message larger than max (<size>vs. 419430400)"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:56826 {grpc_message:"grpc: received message larger than max (<size> vs. 419430400)", grpc_status:8, created_time:"2023-05-28T19:21:14.603349452+00:00"}"
```

`<size>` is close to 550000000.

As it exceeds the gRPC maximum, I am wondering if there is a multi-part upload to chunk the large file into separate parts.

**Comment by muhlba91** [comment]
can you please open an upstream issue in https://github.com/bpg/terraform-provider-proxmox (and reference it here)?

this provider uses a terraform bridge passing everything through to the used upstream terraform module. this looks more like it's an issue when the terraform code tries to send the data to proxmox.

**Comment by muhlba91** [comment]
closed due to upstream issue being resolved.
