### ISSUE TITLE
Support Start/Shutdown Orders

### ISSUE THREAD

**Issue by yoshikakbudto** [muhlba91/pulumi-proxmoxve#82]
I couldnt find how to configure Shutdown timeout with python module. 
I tried to configure it from the Proxmox UI and then do a pulumi refresh to observe how it looks like from "the other side". But i got error:
```
* error retrieving VM: failed to decode HTTP GET response (path: nodes/pve-b2/qemu/100/config) - Reason: json: cannot unmarshal string into Go struct field GetResponseData.data.startup of type vms.CustomStartupOrder
```

In the qemu config file the configured value looks like this:
```
# grep "startup" /etc/pve/qemu-server/100.conf
startup: down=400
```

Is that really unsupported yet or am i missing something?

**Comment by muhlba91** [comment]
this provider is built in the terraform provider https://github.com/bpg/terraform-provider-proxmox. in fact, what the documentation for the terraform provider shows should be working in pulumi as well.

as for your particular question: only `on_boot` is supported which is, unfortunately, only a boolean flag (https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#on_boot).

can you please raise this issue in the upstream terraform provider as that would be the right place to get awareness for this feature? :)
