### ISSUE TITLE
Add SDK/vx.y.z tag for Go package use

### ISSUE THREAD

**Issue by guineveresaenger** [muhlba91/pulumi-proxmoxve#9]
For use with Go, an extra tag prefix of `SDK` is expected by Pulumi for the Go SDK to work.

Example here: https://github.com/pulumi/pulumi-opsgenie/tags

**Comment by muhlba91** [comment]
1. tag for `v2.0.0` created
2. added automated tagging into release pipeline (https://github.com/muhlba91/pulumi-proxmoxve/blob/main/.github/workflows/release.yml#L233)

please verify and close the issue.
